### ISSUE TITLE
Project Feedback!

### ISSUE THREAD

**Issue by codepathreview** [ArenAshikian/Flixter#2]
It looks like the following features are not reflected on your GIF walkthrough: 

- **Not Shown** User Story 3: Display a nice default placeholder graphic for each image during loading

In order for us to count these towards your submission, please record another GIF that captures these features. Once you do, please push your updates and **submit your assignment again through the course portal within 48 hours from the posted deadline so that we can regrade it**.

**Comment by ArenAshikian** [comment]
The feature in question was an accidental checkmark on my part. I had no
intention of creating a default placeholder graphic for each image at this
time.

Do I need to resubmit even though I made no changes? Please let me know!

~Aren Ashikian

**Comment by codepathreview** [comment]
Hello Aren, 

Thanks for reaching back to us. There is no need to resubmit the assignment. Thanks for clearing the confusion. Happy coding!
